import * as cache from "@actions/cache";
import * as core from "@actions/core";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Subdirectories of $OCX_HOME worth caching across runs.
 *
 * - `blobs`    raw content-addressable storage (layer bytes)
 * - `layers`   extracted layer trees (the heavy directory, ~hundreds of MB)
 * - `packages` package-root directories that PATH entries point into
 * - `tags`     local tag→digest index, needed for offline resolve
 *
 * Skipped: `symlinks/`, `projects/` (regenerated by `ocx pull` / `ocx env`),
 * `state/`, `temp/` (run-local). Mirrors `Swatinem/rust-cache` /
 * `astral-sh/setup-uv` precedent of caching the CAS, not the volatile farm.
 */
export const CACHED_DIRS = ["blobs", "layers", "packages", "tags"] as const;

export interface ObjectStoreCacheConfig {
  ocxHome: string;
  lockFile: string;
  ocxVersion: string;
  libc: string;
  cacheSuffix: string;
}

/**
 * SHA256 of the file contents, hex encoded.
 * Returns `nolock` when the file is missing — keeps the cache key stable for
 * projects shipped without a lock (`ocx pull` will error before we ever
 * read the cache, so the bogus key is harmless).
 */
export function hashFile(filePath: string): string {
  try {
    const data = fs.readFileSync(filePath);
    return crypto.createHash("sha256").update(data).digest("hex");
  } catch {
    return "nolock";
  }
}

export function buildCacheKey(cfg: ObjectStoreCacheConfig): string {
  const lock = hashFile(cfg.lockFile).slice(0, 16);
  const suffix = cfg.cacheSuffix ? `-${cfg.cacheSuffix}` : "";
  return `setup-ocx-store-${process.platform}-${process.arch}-${cfg.libc}-ocx${cfg.ocxVersion}-${lock}${suffix}`;
}

/**
 * Restore-key fallback chain. Tries progressively looser keys so a lock churn
 * still gets a partial hit (object store is content-addressable — extra blobs
 * are harmless, missing ones get fetched by `ocx pull`).
 */
export function restoreKeys(cfg: ObjectStoreCacheConfig): string[] {
  const suffix = cfg.cacheSuffix ? `-${cfg.cacheSuffix}` : "";
  return [
    `setup-ocx-store-${process.platform}-${process.arch}-${cfg.libc}-ocx${cfg.ocxVersion}-${suffix ? suffix.slice(1) + "-" : ""}`,
    `setup-ocx-store-${process.platform}-${process.arch}-${cfg.libc}-`,
  ];
}

function cachePaths(ocxHome: string): string[] {
  return CACHED_DIRS.map((d) => path.join(ocxHome, d));
}

export interface RestoreResult {
  key: string;
  hit: boolean;
  matchedKey?: string;
}

export async function restoreObjectStoreCache(cfg: ObjectStoreCacheConfig): Promise<RestoreResult> {
  const key = buildCacheKey(cfg);
  if (!cache.isFeatureAvailable()) {
    core.warning(
      "@actions/cache feature not available on this runner; skipping object store cache.",
    );
    return { key, hit: false };
  }

  // Pre-create the cached directories so restoreCache has stable targets.
  fs.mkdirSync(cfg.ocxHome, { recursive: true });
  for (const dir of cachePaths(cfg.ocxHome)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  try {
    const matched = await cache.restoreCache(cachePaths(cfg.ocxHome), key, restoreKeys(cfg));
    if (matched) {
      core.info(`Restored OCX object store cache (matched key: ${matched})`);
      return { key, hit: matched === key, matchedKey: matched };
    }
    core.info(`No OCX object store cache entry for key ${key}`);
    return { key, hit: false };
  } catch (err) {
    core.warning(
      `Failed to restore OCX object store cache: ${err instanceof Error ? err.message : String(err)}`,
    );
    return { key, hit: false };
  }
}

export async function saveObjectStoreCache(ocxHome: string, key: string): Promise<void> {
  if (!cache.isFeatureAvailable()) {
    return;
  }
  try {
    core.info(`Saving OCX object store cache (key=${key})...`);
    await cache.saveCache(cachePaths(ocxHome), key);
  } catch (err) {
    core.warning(
      `Failed to save OCX object store cache: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}
