name: Release

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        id: changelog
        uses: orhun/git-cliff-action@c93ef52f3d0ddcdcc9bd5447d98d458a11cd4f72 # v4
        with:
          args: --latest --strip header
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v2
        with:
          body: ${{ steps.changelog.outputs.content }}
          make_latest: true

      - name: Update major version tag
        env:
          TAG: ${{ github.ref_name }}
        run: |
          major="${TAG%%.*}"
          git tag -f "$major"
          git push origin "$major" --force
